FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
FROM nginx:stable-alpine
# Copy React build to nginx default html folder
COPY --from=build /app/build /usr/share/nginx/html
# Optional: copy default config (nginx will use it automatically)
# COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]