services:
  backend:
    build: ./backend
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - PYTHONPATH=/app
      - DATABASE_URI=mongodb+srv://bcraig:ZQHTDUgLK3plipmC@ram.ywxt11j.mongodb.net/
      - FLASK_DEBUG=TRUE
      - FLASK_SECRET_KEY=liausdhflwerio8yfljshdlfho8we7fgwle90fywe98fhbweoufpiwe
      - EMAIL_PASSWORD=qhzwcqsygnyysclo
    volumes:
      - ./backend/large_files_db:/app/large_files_db

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true