FROM python:3.12
WORKDIR /backend
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn
COPY . .
RUN mkdir -p large_files_db/images large_files_db/reports
EXPOSE 5000
CMD ["python", "-m", "gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "main:create_app()"]
